### ISSUE TITLE
libtcl needs version number in Makefile

### ISSUE THREAD

**Issue by ewdijkstra** [HeRCLab/nocsim#19]
Need to do this before you can build, even after executing the commands in the dockerfile:
sed 's/-ltcl/-ltcl8.6/g' -i Makefile

**Comment by charlesdaniels** [comment]
Was this against master or dev?

**Comment by charlesdaniels** [comment]
should be fixed as of f3963ae42fd89b0badea26715f76f914bb1af2c9 re-open if not
