### ISSUE TITLE
use hashtable for nocsim_node_by_id

### ISSUE THREAD

**Issue by charlesdaniels** [HeRCLab/nocsim#5]
The [nocsim_node_by_id](https://github.com/HeRCLab/nocsim/blob/ffa2851d5295aa1d7cfaa67bd1ef9eb3aa0f7df6/src/util.c#L156) function currently works via linear search through all nodes. For performance reasons, this information should be stored in a hash table attached to `state`.

The hash table should be initialized [here](https://github.com/HeRCLab/nocsim/blob/ffa2851d5295aa1d7cfaa67bd1ef9eb3aa0f7df6/src/interp.c#L710).

A suitable open source hash table implementation should be found and added to the source tree. Don't forget to symlink any new files in `src` into `gui/src`.

**Comment by philipaconrad** [comment]
I've found a few different hash table implementations out there:

 - The POSIX/GNU [hsearch][hsearch] API.
 - An [implementation][jroutley-impl] on Github by a guy, which has a [tutorial][jroutley-tutorial] showing step-by-step how it was constructed.
 - [SGLIB][sglib]

Of course, it's always an option to roll-your-own hash table, using a decent hash function, such as the [Fowler-Noll-Vo hash function][fnv-hash], which seems to be popular in some circles.

   [hsearch]: https://linux.die.net/man/3/hsearch
   [jroutley-impl]: https://github.com/jamesroutley/algorithms-and-data-structures/tree/master/hash-table
   [jroutley-tutorial]: https://github.com/jamesroutley/write-a-hash-table
   [sglib]: http://sglib.sourceforge.net/
   [fnv-hash]: https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function

**Comment by charlesdaniels** [comment]
There are also a few mentioned [here](https://github.com/nothings/single_file_libs). If `hsearch` is in POSIX, or at least wide used, it's probably the safest bet.

**Comment by philipaconrad** [comment]
It looks like `hsearch` landed in the POSIX.1-2001 standard, and is pulled in from a `<search.h>` header, so go figure. It might be good, it might be garbage.

I'll look at the single-file implementations to see if any of those are good. I'd prefer to drag only a minimum amount of extra code into the codebase if possible.

**Comment by charlesdaniels** [comment]
If `hsearch` is any good, then I would use that. OpenBSD has it, so it's spread out pretty well, as they are usually quite conservative with adding new stuff.

**Comment by philipaconrad** [comment]
On that page you linked, two seem pretty good:

 - [uthash][uthash] seems quite popular, and includes a hash table implementation.
 - [klib][klib] includes a hash table implementation as well, and the hash table can be used independently of the other libraries in the set. (I like this one better of the two.)

   [uthash]: https://github.com/troydhanson/uthash
   [klib]: http://attractivechaos.github.io/klib/

**Comment by philipaconrad** [comment]
Okay, I've got some WIP stuff up on the `add-hash-table` branch using `khash`.
