### ISSUE TITLE
internal router buffers

### ISSUE THREAD

**Issue by charlesdaniels** [HeRCLab/nocsim#7]
Routers should have a "backlog" FIFO, where the `route` command would allow a router to insert a flit into it's internal buffer, rather than sending it to an outgoing link. With respect to the TCL scripting interface, the router's internal buffer should be treated as a direction, and the `nocsim_direction` enum should be expanded to support this.

(EDIT by @philipaconrad)
TODO:
 - [x] Rename ptr to flit list.
 - [x] Initialize flit list for routers.
 - [x] Add buffer to/from handling to the `route` command.
     - [ ] Handle issue #9
 - [ ] Add warning about non-empty buffers on simulation shutdown.
 - [ ] Add performance counter `flits_in_buffers` that is calculated each step (exposed as a magic variable).
 - [x] Add buffer support to the `drop` command.
    - [ ] Add test for buffer `drop` support.
 - [x] Add buffer support to the `peek` command.
    - [ ] Add test for buffer `peek` support.
 - [x] Unit test case(s).

**Comment by charlesdaniels** [comment]
Somewhat more detailed plan here:

The `nocsim_node` type already has a pointer to a `vec_T(nocsim_flit)` that is used for PEs to store their outgoing flits that are pending on injection. That might be re-usable for the purpose of the router buffers, since for nodes of type router, this structure is initialized to `NULL` currently.

`nocsim_direction` needs to be expanded because `route` uses internal integer direction values, rather than their string equivalents. The new value should not be contiguous with the `NSEWP` values and should probably come after `DIR_UNDEF` and have a very high value. This is because `for (nocsim_direction d = N ; d < DIR_UNDEF ; d++)` is a common pattern and should nto break.

Remember to appropriately expand the `NOCSIM_DIRECTION_TO_STR` and `NOCSIM_STR_TO_DIRECTION` macros with the new value.

Also, failing to route a flit out of the internal buffer, or routing multiple flits from the internal buffer are both not error conditions and should not crash.

**Comment by philipaconrad** [comment]
Thanks for summarizing our earlier discussion! Those notes will be helpful as I implement this stuff.

**Comment by philipaconrad** [comment]
Added some TODOs for myself, to help keep track of what's left.

**Comment by charlesdaniels** [comment]
There should be a new performance counter in `nocsim_state` which is the total number of flits in all buffers. This can be zeroed at the beginning of each new simulation step, and summed up over the course of the tick in `simulation.c`. It should be exposed as a read-only magic variable. You probably want to implement this using a read-only bound variable inside of the setup function in `interp.c`.

**Comment by charlesdaniels** [comment]
Closed in 0637e6fcb9d55c9a909bc18e32f2383e2667a6de
